# Generated by Django 5.2 on 2025-12-09 13:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, unique=True)),
                ('ordre', models.PositiveIntegerField(help_text="Ordre d'affichage (1 pour L1, 2 pour L2, etc.)", unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('capacite', models.PositiveIntegerField()),
                ('batiment', models.CharField(blank=True, max_length=50, null=True)),
                ('etage', models.CharField(blank=True, max_length=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Matricule invalide. Caractères autorisés: lettres majuscules, chiffres et tirets.', regex='^[A-Z0-9\\-]+$')])),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide', regex='^\\+?[0-9\\s\\-\\(\\)]{8,20}$')])),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('exclu', 'Exclu'), ('diplome', 'Diplômé')], default='actif', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='etudiants/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filiere')),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.niveau')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['matricule'],
                'permissions': [('can_view_all_students', 'Peut voir tous les étudiants'), ('can_export_students', 'Peut exporter les données étudiants')],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('montant_attendu', models.IntegerField(default=0)),
                ('est_regle', models.BooleanField(default=False)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneeacademique')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etudiant')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='SessionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_session', models.CharField(choices=[('normale', 'Session Normale'), ('rattrapage', 'Session de Rattrapage')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneeacademique')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'examen",
                'verbose_name_plural': "Sessions d'examen",
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('intitule', models.CharField(max_length=255)),
                ('semestre', models.PositiveIntegerField()),
                ('credit', models.PositiveIntegerField(default=6)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveau')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement",
                'verbose_name_plural': "Unités d'Enseignement",
                'ordering': ['niveau__ordre', 'semestre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('est_autorise_examen', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneeacademique')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_crees', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etudiant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ue')),
            ],
            options={
                'verbose_name': 'Inscription UE',
                'verbose_name_plural': 'Inscriptions UE',
                'permissions': [('can_authorize_exam', 'Peut autoriser un étudiant à passer un examen')],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_examen', models.CharField(choices=[('normal', 'Session Normale'), ('rattrapage', 'Session de Rattrapage')], default='normal', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneeacademique')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_crees', to=settings.AUTH_USER_MODEL)),
                ('surveillant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salle')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sessionexamen')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ue')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['date', 'heure_debut'],
                'permissions': [('can_manage_exams', 'Peut gérer les examens'), ('can_assign_supervisor', 'Peut assigner des surveillants')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('scan', "Scan d'accès"), ('paiement', 'Paiement'), ('inscription', 'Inscription UE'), ('examen', 'Création/Modification examen'), ('justificatif', 'Traitement justificatif'), ('system', 'Action système'), ('connexion', 'Connexion/Déconnexion'), ('export', 'Export de données')], max_length=20)),
                ('action', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'action_type'], name='core_auditl_timesta_b3745a_idx'), models.Index(fields=['utilisateur', 'timestamp'], name='core_auditl_utilisa_1fd7b2_idx'), models.Index(fields=['action_type', 'timestamp'], name='core_auditl_action__64f4df_idx')],
            },
        ),
        migrations.CreateModel(
            name='ControleAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_method', models.CharField(choices=[('qr', 'QR Code'), ('matricule', 'Matricule'), ('manuel', 'Entrée manuelle')], default='qr', max_length=20)),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
                ('autorise', models.BooleanField(default=False)),
                ('raison_refus', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etudiant')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examen')),
            ],
            options={
                'verbose_name': "Contrôle d'accès",
                'verbose_name_plural': "Contrôles d'accès",
                'permissions': [('can_scan_qr', 'Peut scanner les QR codes')],
                'indexes': [models.Index(fields=['examen', 'date_scan'], name='core_contro_examen__8831ed_idx'), models.Index(fields=['etudiant', 'autorise'], name='core_contro_etudian_056f40_idx'), models.Index(fields=['date_scan', 'scan_method'], name='core_contro_date_sc_569347_idx')],
                'unique_together': {('examen', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='JustificatifAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_justificatif', models.CharField(choices=[('medical', 'Médical'), ('familial', 'Familial'), ('administratif', 'Administratif'), ('autre', 'Autre')], default='medical', max_length=20)),
                ('fichier', models.FileField(upload_to='justificatifs/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_traitement', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etudiant')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examen')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Justificatif d'absence",
                'verbose_name_plural': "Justificatifs d'absence",
                'ordering': ['-date_depot'],
                'permissions': [('can_process_justificatif', "Peut traiter les justificatifs d'absence")],
                'indexes': [models.Index(fields=['etudiant', 'statut'], name='core_justif_etudian_843516_idx'), models.Index(fields=['examen', 'statut'], name='core_justif_examen__531e4e_idx')],
                'unique_together': {('etudiant', 'examen')},
            },
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['matricule', 'statut'], name='core_etudia_matricu_a4ad1e_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['filiere', 'niveau'], name='core_etudia_filiere_eadf27_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['etudiant', 'annee_academique'], name='core_paieme_etudian_0eaf93_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['est_regle', 'annee_academique'], name='core_paieme_est_reg_5f3281_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paiement',
            unique_together={('etudiant', 'annee_academique')},
        ),
        migrations.AddIndex(
            model_name='sessionexamen',
            index=models.Index(fields=['type_session', 'active'], name='core_sessio_type_se_834bed_idx'),
        ),
        migrations.AddIndex(
            model_name='ue',
            index=models.Index(fields=['filiere', 'niveau'], name='core_ue_filiere_8c1a11_idx'),
        ),
        migrations.AddIndex(
            model_name='ue',
            index=models.Index(fields=['code', 'semestre'], name='core_ue_code_d901c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ue',
            unique_together={('code', 'filiere')},
        ),
        migrations.AddIndex(
            model_name='inscriptionue',
            index=models.Index(fields=['etudiant', 'annee_academique'], name='core_inscri_etudian_b2571f_idx'),
        ),
        migrations.AddIndex(
            model_name='inscriptionue',
            index=models.Index(fields=['ue', 'annee_academique'], name='core_inscri_ue_id_84c341_idx'),
        ),
        migrations.AddIndex(
            model_name='inscriptionue',
            index=models.Index(fields=['est_autorise_examen', 'annee_academique'], name='core_inscri_est_aut_1f5870_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscriptionue',
            unique_together={('etudiant', 'ue', 'annee_academique')},
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['date', 'salle'], name='core_examen_date_772f75_idx'),
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['ue', 'annee_academique'], name='core_examen_ue_id_44bd25_idx'),
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['session', 'type_examen'], name='core_examen_session_840802_idx'),
        ),
    ]
